### ISSUE TITLE
Creating issue while modeling

### ISSUE THREAD

**Issue by jatinkhatri** [nikku/bpmn-js-cli-modeling-dsl#6]
I am getting issue while modeling via given command:

`cli.model("StartEvent_1 -> bpmn:Participant -> bpmn:Lane");`

I need to create a diagram as shown below.

![BPMN-snip](https://user-images.githubusercontent.com/5096571/103332898-e48b9b80-4a91-11eb-966f-1f8358708c20.PNG)

**Comment by nikku** [comment]
Modeling participants and lanes is currently not supported I believe. 

So the following won't work:

```
cli.model("StartEvent_1 -> bpmn:Participant -> bpmn:Lane");
```

Why do you plan to create such a complex process using the CLI?

**Comment by jatinkhatri** [comment]
Is there any way to make diagrams programmatically ?

**Comment by nikku** [comment]
> Why do you plan to create such a complex process using the CLI?
